# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/qingchu/fun/Smarthome/code/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1782, 963)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(990, 130, 701, 721))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.CalendarText_d = QtWidgets.QTextBrowser(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.CalendarText_d.sizePolicy().hasHeightForWidth())
        self.CalendarText_d.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.CalendarText_d.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.CalendarText_d.setFont(font)
        self.CalendarText_d.setObjectName("CalendarText_d")
        self.CalendarText_dmy = QtWidgets.QTextBrowser(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.CalendarText_dmy.sizePolicy().hasHeightForWidth())
        self.CalendarText_dmy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CalendarText_dmy.setFont(font)
        self.CalendarText_dmy.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CalendarText_dmy.setObjectName("CalendarText_dmy")
        self.listWidget = QtWidgets.QListWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(237, 212, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.splitter_3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1150, 10, 191, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photolabel_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.photolabel_1.setText("")
        self.photolabel_1.setObjectName("photolabel_1")
        self.horizontalLayout_3.addWidget(self.photolabel_1)
        self.photolabel_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.photolabel_3.setText("")
        self.photolabel_3.setObjectName("photolabel_3")
        self.horizontalLayout_3.addWidget(self.photolabel_3)
        self.photolabel_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.photolabel_4.setText("")
        self.photolabel_4.setObjectName("photolabel_4")
        self.horizontalLayout_3.addWidget(self.photolabel_4)
        self.photolabel_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.photolabel_2.setText("")
        self.photolabel_2.setObjectName("photolabel_2")
        self.horizontalLayout_3.addWidget(self.photolabel_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(360, 920, 254, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_stop = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.pushButton_record = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_record.setObjectName("pushButton_record")
        self.horizontalLayout_2.addWidget(self.pushButton_record)
        self.pushButton_read = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_read.setObjectName("pushButton_read")
        self.horizontalLayout_2.addWidget(self.pushButton_read)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 70, 941, 841))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphWidget_pm25 = PlotWidget(self.layoutWidget3)
        self.graphWidget_pm25.setEnabled(False)
        self.graphWidget_pm25.setObjectName("graphWidget_pm25")
        self.gridLayout.addWidget(self.graphWidget_pm25, 0, 1, 1, 1)
        self.graphWidget_pm10 = PlotWidget(self.layoutWidget3)
        self.graphWidget_pm10.setEnabled(False)
        self.graphWidget_pm10.setObjectName("graphWidget_pm10")
        self.gridLayout.addWidget(self.graphWidget_pm10, 1, 1, 1, 1)
        self.graphWidget_temp = PlotWidget(self.layoutWidget3)
        self.graphWidget_temp.setEnabled(False)
        self.graphWidget_temp.setObjectName("graphWidget_temp")
        self.gridLayout.addWidget(self.graphWidget_temp, 0, 0, 1, 1)
        self.graphWidget_humi = PlotWidget(self.layoutWidget3)
        self.graphWidget_humi.setEnabled(False)
        self.graphWidget_humi.setObjectName("graphWidget_humi")
        self.gridLayout.addWidget(self.graphWidget_humi, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My smart home"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Meeting"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "12:00 PM-1:00 PM\n"
""))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Meeting 2"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "1:00 PM-2:00 PM\n"
""))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_stop.setText(_translate("MainWindow", "stop"))
        self.pushButton_record.setText(_translate("MainWindow", "Record"))
        self.pushButton_read.setText(_translate("MainWindow", "Read"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
